// Adapter for southleft/figma-console-mcp.
//
// Status: INTERFACE STUB. The actual transport (WebSocket Desktop Bridge
// or Cloudflare Workers paired mode) lives in figma-console-mcp itself.
// This module defines the shape we expect to call so the rest of the
// pipeline (emit, validate) can be developed independently.
//
// See: https://github.com/southleft/figma-console-mcp

import type {
  AgenticSpec,
  TokensContract,
  TokenEntry,
} from "../types/spec.js";

/** A node selected in the Figma file, or a file/node URL. */
export interface FigmaTarget {
  /** Full figma.com URL pointing at a node */
  url?: string;
  /** Or: explicit file_key + node_id */
  file_key?: string;
  node_id?: string;
}

/** The minimum shape we need back from figma-console-mcp to build a spec. */
export interface FigmaComponentSnapshot {
  name: string; // "Button"
  component_set?: string; // "Button"
  node_id: string;
  url: string;
  variant_count: number;
  /**
   * Variables bound to this component, in Figma's flat variable form. We
   * convert these into our TokenEntry format.
   */
  variables: Array<{
    name: string; // "action/primary"
    type: "COLOR" | "FLOAT" | "STRING" | "BOOLEAN";
    value_light?: string | number;
    value_dark?: string | number;
    primitive_ref?: string;
  }>;
  /** ARIA hints if present in component description / dev-ready notes. */
  aria_hints?: string[];
  /** Variant property names (size, intent, state, ...). */
  variant_properties?: Record<string, string[]>;
}

/**
 * Resolve a Figma target via the figma-console-mcp server.
 *
 * Wire-up: the caller passes an MCP client. We do NOT bundle the MCP client
 * here — different agents (Claude Code, Cursor) bring their own. This keeps
 * `agentic-spec` decoupled from any specific MCP transport.
 */
export interface McpClient {
  callTool(
    name: string,
    args: Record<string, unknown>,
  ): Promise<unknown>;
}

export async function fetchComponentSnapshot(
  client: McpClient,
  target: FigmaTarget,
): Promise<FigmaComponentSnapshot> {
  // Expected figma-console-mcp tools (see its README):
  //   get_design_context     — anatomy + structure of selected node
  //   get_variables          — color/float/string variables bound here
  //   get_metadata           — node id, variant counts, component-set info
  //
  // The shape returned below is what an adapter would assemble from those
  // three calls. The actual call is left to the host agent.
  const [_ctx, _vars, _meta] = await Promise.all([
    client.callTool("get_design_context", { target }),
    client.callTool("get_variables", { target }),
    client.callTool("get_metadata", { target }),
  ]);

  // TODO: real assembly. For now, throw so consumers don't get a half-baked
  // snapshot they think is real.
  throw new Error(
    "fetchComponentSnapshot: figma-console-mcp wiring is stubbed. " +
      "Implement the response→FigmaComponentSnapshot mapping in your host. " +
      "See ROADMAP.md.",
  );
}

// ──────────────────────────────────────────────────────────────────────────
// Snapshot → AgenticSpec mapping
// ──────────────────────────────────────────────────────────────────────────

export interface MapOptions {
  ds_version: string;
  code_path?: string;
  framework?: string;
  underlying_library?: string;
  storybook_path?: string;
  tokens_paths?: {
    primitives?: string;
    semantic_light?: string;
    semantic_dark?: string;
  };
  /** Source URL for tokens.json (your repo, typically) */
  tokens_source: string;
}

export function snapshotToSpec(
  snapshot: FigmaComponentSnapshot,
  options: MapOptions,
): { spec: AgenticSpec; tokens: TokensContract } {
  const component = kebab(snapshot.name);
  const today = new Date().toISOString().slice(0, 10);

  const tokenEntries: TokenEntry[] = snapshot.variables.map((v) => ({
    name: v.name.replace(/\//g, "."),
    tier: "semantic", // Figma variables are semantic by convention
    role: inferRole(v.name),
    path: v.name.replace(/\//g, "."),
    primitive: v.primitive_ref,
    light: typeof v.value_light === "string" ? v.value_light : undefined,
    dark: typeof v.value_dark === "string" ? v.value_dark : undefined,
    status: "existing",
  }));

  const tokens: TokensContract = {
    $schema: "../../_templates/component/tokens.schema.json",
    component,
    source: options.tokens_source,
    version: options.ds_version,
    verified: today,
    fork_model:
      "Tokens extracted from Figma variables. Bindings preserved 1:1.",
    notes: [
      `Generated by agentic-spec from Figma node ${snapshot.node_id}`,
    ],
    tokens: tokenEntries,
  };

  const interactionStates = inferStatesFromVariants(snapshot.variant_properties);

  const spec: AgenticSpec = {
    component,
    ds_version: options.ds_version,
    status: "Draft",
    last_verified: today,
    category: "Component",
    required_aria: snapshot.aria_hints ?? [],
    semantic_parts: {
      root: "Outer interactive element — owns focus ring and base styles",
      label: "Text content",
    },
    token_contract: tokenEntries.map((t) => t.name),
    interaction_states: interactionStates,
    checks: {
      aria_correct: false,
      structure_correct: false,
      states_complete: false,
      tokens_valid: false,
      no_invented_styles: false,
    },
    sources: {
      code: options.code_path
        ? {
            path: options.code_path,
            framework: options.framework,
            underlying_library: options.underlying_library,
          }
        : undefined,
      storybook: options.storybook_path
        ? { path: options.storybook_path }
        : undefined,
      tokens: options.tokens_paths,
      figma: {
        component_set: snapshot.component_set,
        node_id: snapshot.node_id,
        url: snapshot.url,
        variant_count: snapshot.variant_count,
      },
    },
    patterns_used_in: [],
    pages_used_in: [],
  };

  return { spec, tokens };
}

// ── helpers ───────────────────────────────────────────────────────────────

function kebab(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/\s+/g, "-")
    .toLowerCase();
}

function inferRole(name: string): string {
  const last = name.split("/").pop() ?? name;
  return last.toLowerCase();
}

function inferStatesFromVariants(
  variants?: Record<string, string[]>,
): string[] {
  if (!variants) return ["default"];
  const stateLike = ["state", "interaction", "status"];
  for (const [k, vs] of Object.entries(variants)) {
    if (stateLike.includes(k.toLowerCase())) {
      return vs.map((v) => v.toLowerCase());
    }
  }
  return ["default"];
}
