import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { stringify as yamlStringify } from "yaml";
import type { AgenticSpec, TokensContract } from "../types/spec.js";

/**
 * Emit an agentic spec to disk.
 *
 *   <outDir>/<component>/index.md     — frontmatter + prose body
 *   <outDir>/<component>/tokens.json  — token contract
 *
 * `prose` is the markdown body that follows the frontmatter. If omitted, a
 * skeleton with placeholder sections is generated so a human (or agent) can
 * fill it in.
 */
export async function emitSpec(
  outDir: string,
  spec: AgenticSpec,
  tokens: TokensContract,
  prose?: string,
): Promise<{ specPath: string; tokensPath: string }> {
  const componentDir = join(outDir, spec.component);
  await mkdir(componentDir, { recursive: true });

  const frontmatter = yamlStringify(spec, { lineWidth: 0 });
  const body = prose ?? skeletonProse(spec);
  const indexMd = `---\n${frontmatter}---\n\n${body}\n`;

  const specPath = join(componentDir, "index.md");
  const tokensPath = join(componentDir, "tokens.json");

  await writeFile(specPath, indexMd, "utf8");
  await writeFile(tokensPath, JSON.stringify(tokens, null, 2) + "\n", "utf8");

  return { specPath, tokensPath };
}

function skeletonProse(spec: AgenticSpec): string {
  const name = spec.component.toUpperCase();
  const partsList = Object.keys(spec.semantic_parts)
    .map((p) => `- \`${p}\``)
    .join("\n");
  const statesList = spec.interaction_states.map((s) => `- \`${s}\``).join("\n");

  return `# AGENTIC DOCUMENTATION: ${name}

> **Status:** ${spec.status}. Generated by \`agentic-spec\` on ${spec.last_verified}. The frontmatter above is the machine contract; this prose explains it for humans.

## 1. Purpose & Intent

<One short paragraph: what the component does, in plain language.>

## 2. Required Contract

### 2.1 Required ARIA

${spec.required_aria.length > 0 ? spec.required_aria.map((a) => `- \`${a}\``).join("\n") : "_None._"}

### 2.2 Semantic parts

${partsList}

### 2.3 Token bindings

See [\`tokens.json\`](./tokens.json) for the closed token contract (${spec.token_contract.length} tokens).

## 3. Interaction States

${statesList}

## 4. Agent Notes

What an AI agent must check before editing this component:

1. Every token referenced in code MUST exist in this spec's \`token_contract\` and in \`tokens.json\`.
2. Every \`interaction_states\` entry needs a Storybook story.
3. Bump \`last_verified\` whenever you reconcile spec ↔ code.
`;
}
